gitops-runtime:
  app-proxy:
    config:
      cors: https://hermes-onprem-test.cf-op.com
    env:
      HELM_REPOSITORY: oci://quay.io/codefresh/dev/gitops-runtime
  argo-cd:
    configs:
      params:
        application.namespaces: ''
    crds:
      install: true
    createClusterRoles: false
  argo-events:
    controller:
      rbac:
        namespaced: true
  argo-rollouts:
    enabled: false
    installCRDs: true
  argo-workflows:
    controller:
      clusterWorkflowTemplates:
        enabled: false
    crds:
      install: true
    createAggregateRoles: false
    server:
      clusterWorkflowTemplates:
        enabled: false
    singleNamespace: true
  gitops-operator:
    crds:
      install: true
    env:
      GITOPS_OPERATOR_VERSION: 0.10.1
  global:
    codefresh:
      accountId: 68b948a4b067a69657fcf2bc
      url: https://hermes-onprem-test.cf-op.com
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      eventBus:
        type: jetstream
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - alina-hermes.rnd-sandbox.cf-infra.com
        protocol: https
        skipValidation: true
      isConfigurationRuntime: true
      name: mnr-1
      singleNamespace: true
  sealed-secrets:
    enabled: false
  tunnel-client:
    enabled: false
